export const SET_SYSTEM_INFO = "SET_SYSTEM_INFO";
export const SET_AUTH_HASH = "SET_AUTH_HASH";
export const SET_HOST_INFO = "SET_HOST_INFO";

export const REMIND_LATER_NOT_UPLOADED = "REMIND_LATER_NOT_UPLOADED";