export const ALL_CASES_FETCH_REQUESTED = "ALL_CASES_FETCH_REQUESTED";
export const ALL_CASES_FETCH_SUCCEEDED = "ALL_CASES_FETCH_SUCCEEDED";
export const ALL_CASES_FETCH_FAILED = "ALL_CASES_FETCH_FAILED";

export const USER_CASES_FETCH_REQUESTED = "USER_CASES_FETCH_REQUESTED";
export const USER_CASES_FETCH_SUCCEEDED = "USER_CASES_FETCH_SUCCEEDED";
export const USER_CASES_FETCH_FAILED = "USER_CASES_FETCH_FAILED";

export const CASE_PARTICIPANTS_FETCH_REQUESTED = "CASE_PARTICIPANTS_FETCH_REQUESTED";
export const CASE_PARTICIPANTS_FETCH_SUCCEEDED = "CASE_PARTICIPANTS_FETCH_SUCCEEDED";
export const CASE_PARTICIPANTS_FETCH_FAILED = "CASE_PARTICIPANTS_FETCH_FAILED";

export const USER_SINGLE_CASE_FETCH_REQUESTED = "USER_SINGLE_CASE_FETCH_REQUESTED";
export const USER_SINGLE_CASE_FETCH_SUCCEEDED = "USER_SINGLE_CASE_FETCH_SUCCEEDED";
export const USER_SINGLE_CASE_FETCH_FAILED = "USER_SINGLE_CASE_FETCH_FAILED";

export const CASE_TYPES_FETCH_REQUESTED = "CASE_TYPES_FETCH_REQUESTED";
export const CASE_TYPES_FETCH_SUCCEEDED = "CASE_TYPES_FETCH_SUCCEEDED";
export const CASE_TYPES_FETCH_FAILED = "CASE_TYPES_FETCH_FAILED";

export const CASE_ROLES_FETCH_REQUESTED = "CASE_ROLES_FETCH_REQUESTED";
export const CASE_ROLES_FETCH_SUCCEEDED = "CASE_ROLES_FETCH_SUCCEEDED";
export const CASE_ROLES_FETCH_FAILED = "CASE_ROLES_FETCH_FAILED";

export const CASE_SIDES_FETCH_REQUESTED = "CASE_SIDES_FETCH_REQUESTED";
export const CASE_SIDES_FETCH_SUCCEEDED = "CASE_SIDES_FETCH_SUCCEEDED";
export const CASE_SIDES_FETCH_FAILED = "CASE_SIDES_FETCH_FAILED";

export const DEPARTMENTS_FETCH_REQUESTED = "DEPARTMENTS_FETCH_REQUESTED";
export const DEPARTMENTS_FETCH_SUCCEEDED = "DEPARTMENTS_FETCH_SUCCEEDED";
export const DEPARTMENTS_FETCH_FAILED = "DEPARTMENTS_FETCH_FAILED";

export const ADD_DEPARTMENT_REQUESTED = "ADD_DEPARTMENT_REQUESTED";
export const ADD_DEPARTMENT_SUCCEEDED = "ADD_DEPARTMENT_SUCCEEDED";
export const ADD_DEPARTMENT_FAILED = "ADD_DEPARTMENT_FAILED";

export const UPDATE_DEPARTMENT_REQUESTED = "UPDATE_DEPARTMENT_REQUESTED";
export const UPDATE_DEPARTMENT_SUCCEEDED = "UPDATE_DEPARTMENT_SUCCEEDED";
export const UPDATE_DEPARTMENT_FAILED = "UPDATE_DEPARTMENT_FAILED";

export const DELETE_DEPARTMENT_REQUESTED = "DELETE_DEPARTMENT_REQUESTED";
export const DELETE_DEPARTMENT_SUCCEEDED = "DELETE_DEPARTMENT_SUCCEEDED";
export const DELETE_DEPARTMENT_FAILED = "DELETE_DEPARTMENT_FAILED";

export const CALENDARS_FETCH_REQUESTED = "CALENDARS_FETCH_REQUESTED";
export const CALENDARS_FETCH_SUCCEEDED = "CALENDARS_FETCH_SUCCEEDED";
export const CALENDARS_FETCH_FAILED = "CALENDARS_FETCH_FAILED";

export const ADD_CALENDAR_REQUESTED = "ADD_CALENDAR_REQUESTED";
export const ADD_CALENDAR_SUCCEEDED = "ADD_CALENDAR_SUCCEEDED";
export const ADD_CALENDAR_FAILED = "ADD_CALENDAR_FAILED";

export const UPDATE_CALENDAR_REQUESTED = "UPDATE_CALENDAR_REQUESTED";
export const UPDATE_CALENDAR_SUCCEEDED = "UPDATE_CALENDAR_SUCCEEDED";
export const UPDATE_CALENDAR_FAILED = "UPDATE_CALENDAR_FAILED";

export const DELETE_CALENDAR_REQUESTED = "DELETE_CALENDAR_REQUESTED";
export const DELETE_CALENDAR_SUCCEEDED = "DELETE_CALENDAR_SUCCEEDED";
export const DELETE_CALENDAR_FAILED = "DELETE_CALENDAR_FAILED";


export const REMOVE_CASE = "REMOVE_CASE";

export const SET_CURRENT_CASE = "SET_CURRENT_CASE";
export const REMOVE_CURRENT_CASE = "REMOVE_CURRENT_CASE";