//	sync_share
export const USER_UPCOMING_EVENTS_FETCH_REQUESTED = "USER_UPCOMING_EVENTS_FETCH_REQUESTED";
export const USER_UPCOMING_EVENTS_FETCH_SUCCEEDED = "USER_UPCOMING_EVENTS_FETCH_SUCCEEDED";
export const USER_UPCOMING_EVENTS_FETCH_FAILED = "USER_UPCOMING_EVENTS_FETCH_FAILED";
