module.exports.SET_SYSTEM_INFO = "SET_SYSTEM_INFO";
module.exports.SET_AUTH_HASH = "SET_AUTH_HASH";
module.exports.SET_IS_BLOCKED_SYNC = "SET_IS_BLOCKED_SYNC";
module.exports.SET_IS_UPLOAD_CONFIRMED = "SET_IS_UPLOAD_CONFIRMED";

module.exports.ADD_FILE_LOCATION = "ADD_FILE_LOCATION";
module.exports.ADD_REGISTERED_FILE = "ADD_REGISTERED_FILE";
module.exports.ADD_NEW_FILE = "ADD_NEW_FILE";
module.exports.ADD_NEW_VERSION = "ADD_NEW_VERSION";
module.exports.ADD_SCANNED_FOLDER = "ADD_SCANNED_FOLDER";
module.exports.REMOVE_LOCATION = "REMOVE_LOCATION";

module.exports.INCREASE_SCANNED_FOLDERS = "INCREASE_SCANNED_FOLDERS";
module.exports.INCREASE_SCANNED_FILES = "INCREASE_SCANNED_FILES";
module.exports.INCREASE_NEW_FILES = "INCREASE_NEW_FILES";
module.exports.INCREASE_NEW_FILES_SIZE = "INCREASE_NEW_FILES_SIZE";

module.exports.SET_DEFAULT_SYNC_STATE = "SET_DEFAULT_SYNC_STATE";

