//	sync_share
export const SYNC_SHARE_FETCH_REQUESTED = "SYNC_SHARE_FETCH_REQUESTED";
export const SYNC_SHARE_FETCH_SUCCEEDED = "SYNC_SHARE_FETCH_SUCCEEDED";
export const SYNC_SHARE_FETCH_FAILED = "SYNC_SHARE_FETCH_FAILED";

export const SYNC_SHARED_PERSONS_FETCH_REQUESTED = "SYNC_SHARED_PERSONS_FETCH_REQUESTED";
export const SYNC_SHARED_PERSONS_FETCH_SUCCEEDED = "SYNC_SHARED_PERSONS_FETCH_SUCCEEDED";
export const SYNC_SHARED_PERSONS_FETCH_FAILED = "SYNC_SHARED_PERSONS_FETCH_FAILED";

export const ADD_SYNC_SHARE_PERSON_REQUESTED = "ADD_SYNC_SHARE_PERSON_REQUESTED";
export const ADD_SYNC_SHARE_PERSON_SUCCEEDED = "ADD_SYNC_SHARE_PERSON_SUCCEEDED";
export const ADD_SYNC_SHARE_PERSON_FAILED = "ADD_SYNC_SHARE_PERSON_FAILED";

export const REMOVE_SYNC_SHARE_PERSON_REQUESTED = "REMOVE_SYNC_SHARE_PERSON_REQUESTED";
export const REMOVE_SYNC_SHARE_PERSON_SUCCEEDED = "REMOVE_SYNC_SHARE_PERSON_SUCCEEDED";
export const REMOVE_SYNC_SHARE_PERSON_FAILED = "REMOVE_SYNC_SHARE_PERSON_FAILED";


//sync schedule
export const SYNC_SCHEDULE_FETCH_REQUESTED = "SYNC_SCHEDULE_FETCH_REQUESTED";
export const SYNC_SCHEDULE_FETCH_SUCCEEDED = "SYNC_SCHEDULE_FETCH_SUCCEEDED";
export const SYNC_SCHEDULE_FETCH_FAILED = "SYNC_SCHEDULE_FETCH_FAILED";

export const SET_SYNC_SCHEDULE_FETCH_REQUESTED = "SET_SYNC_SCHEDULE_FETCH_REQUESTED";
export const SET_SYNC_SCHEDULE_FETCH_SUCCEEDED = "SET_SYNC_SCHEDULE_FETCH_SUCCEEDED";
export const SET_SYNC_SCHEDULE_FETCH_FAILED = "SET_SYNC_SCHEDULE_FETCH_FAILED";

export const REMOVE_SYNC_SCHEDULE_REQUESTED = "REMOVE_SYNC_SCHEDULE_REQUESTED";
export const REMOVE_SYNC_SCHEDULE_SUCCEEDED = "REMOVE_SYNC_SCHEDULE_SUCCEEDED";
export const REMOVE_SYNC_SCHEDULE_FAILED = "REMOVE_SYNC_SCHEDULE_FAILED";

//	sync_parsing_steps
export const PARSING_STEPS_FETCH_REQUESTED = "PARSING_STEPS_FETCH_REQUESTED";
export const PARSING_STEPS_FETCH_SUCCEEDED = "PARSING_STEPS_FETCH_SUCCEEDED";
export const PARSING_STEPS_FETCH_FAILED = "PARSING_STEPS_FETCH_FAILED";

//SYNC PROCESS
export const SET_SYNC_PROCESS = "SET_SYNC_PROCESS";
