export const PERSONNEL_FETCH_REQUESTED = "PERSONNEL_FETCH_REQUESTED";
export const PERSONNEL_FETCH_SUCCEEDED = "PERSONNEL_FETCH_SUCCEEDED";
export const PERSONNEL_FETCH_FAILED = "PERSONNEL_FETCH_FAILED";

export const ROLES_FETCH_REQUESTED = "ROLES_FETCH_REQUESTED";
export const ROLES_FETCH_SUCCEEDED = "ROLES_FETCH_SUCCEEDED";
export const ROLES_FETCH_FAILED = "ROLES_FETCH_FAILED";