export const DOCUMENTS_INFO_FETCH_REQUESTED = "DOCUMENTS_INFO_FETCH_REQUESTED";
export const DOCUMENTS_INFO_FETCH_SUCCEEDED = "DOCUMENTS_INFO_FETCH_SUCCEEDED";
export const DOCUMENTS_INFO_FETCH_FAILED = "DOCUMENTS_INFO_FETCH_FAILED";

export const DOCUMENT_FILES_FETCH_REQUESTED = "DOCUMENT_FILES_FETCH_REQUESTED";
export const DOCUMENT_FILES_FETCH_SUCCEEDED = "DOCUMENT_FILES_FETCH_SUCCEEDED";
export const DOCUMENT_FILES_FETCH_FAILED = "DOCUMENT_FILES_FETCH_FAILED";

export const DOC_FORMS_FETCH_REQUESTED = "DOC_FORMS_FETCH_REQUESTED";
export const DOC_FORMS_FETCH_SUCCEEDED = "DOC_FORMS_FETCH_SUCCEEDED";
export const DOC_FORMS_FETCH_FAILED = "DOC_FORMS_FETCH_FAILED";

export const DOC_KEYWORDS_FETCH_REQUESTED = "DOC_KEYWORDS_FETCH_REQUESTED";
export const DOC_KEYWORDS_FETCH_SUCCEEDED = "DOC_KEYWORDS_FETCH_SUCCEEDED";
export const DOC_KEYWORDS_FETCH_FAILED = "DOC_KEYWORDS_FETCH_FAILED";