export const ADD_PROGRESS_MODAL = "ADD_PROGRESS_MODAL";
export const ADD_PROGRESS_MODALS = "ADD_PROGRESS_MODALS";
export const TOGGLE_PROGRESS_MODAL = "TOGGLE_PROGRESS_MODAL";
export const SHOW_PROGRESS_MODAL = "SHOW_PROGRESS_MODAL";
export const HIDE_PROGRESS_MODAL = "HIDE_PROGRESS_MODAL";
export const UPDATE_PROGRESS_MODAL = "UPDATE_PROGRESS_MODAL";